schema_version = "1.0.0"
id = "jewelcraft"
version = "2.17.3"
name = "JewelCraft"
tagline = "Jewelry design toolkit"
maintainer = "Mikhail Rachinskiy"
type = "add-on"
tags = ["Modeling"]
blender_version_min = "4.2.0"
website = "https://github.com/mrachinskiy/jewelcraft"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2015-2025 Mikhail Rachinskiy"]

[permissions]
files = "Manage asset library"
